# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mit-borderline-app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for mit-borderline-app
  
  source 'https://github.com/CocoaPods/Specs.git'
  use_frameworks!
  pod 'SwiftyGif'

  target 'mit-borderline-appTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'mit-borderline-appUITests' do
    # Pods for testing
  end

end
